{% set name = "pyEX" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d364838f4d862d64e9e42ed0fc050b01662b16ee32441541fdfa8c9bb586d722

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - deprecation >=2.0.6
    - ipython >=7.2.0
    - Pillow >=5.3.0
    - pandas >=0.22
    - pytz >=2019.1
    - requests >=2.21.0
    - socketIO-client-nexus >=0.7.6
    - sseclient >=0.0.22
    - temporal-cache >=0.1.1

test:
  imports:
    - pyEX

about:
  home: http://github.com/timkpaine/pyEX
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python interface to IEX and IEX cloud APIs

  description: |
    Python interface to IEX and IEX cloud APIs
  dev_url: https://github.com/timkpaine/pyEX

extra:
  recipe-maintainers:
    - timkpaine
